### ISSUE TITLE
Error in getDatrasExchange for BTS in some years

### ISSUE THREAD

**Issue by iagomosqueira** [DTUAqua/DATRAS#14]
Rerunning code that used to work

```
library(DATRAS)
bts <- getDatrasExchange("BTS", years=seq(1985, 2022), quarters=3, strict=FALSE)
```

and it stops with

```
Error in addExtraVariables(d) :
  nlevels(d3$haul.id) == nrow(d2) is not TRUE
```

It works if years equals `seq(2003,2022)`, for example. It also works 1985:2022 for SNS, so something in BTS data causes it.

I can download the CAS, HH and HL elements for BTS 1985:2022 using icesDATRAS, but wanted to get the rawDATRAS object easily.

**Comment by iagomosqueira** [comment]
When it gets to this line

```
d3$haul.id <- factor(d3$haul.id, levels = levels(d2$haul.id))
```

it finds a discrepancy between both hauld.id fields

```
DATRAS/R/read_datras.R#508: d3$haul.id <- factor(d3$haul.id, levels = levels(d2$haul.id))
Browse[4]> length(unique(d3$haul.id))
[1] 14007
Browse[4]> length(unique(d2$haul.id))
[1] 19871
```

which leads to a stop

```
DATRAS/R/read_datras.R#513: stopifnot(nlevels(d3$haul.id) == nrow(d2))
```

Is maybe the haul.id created at the start not valid anymore due to some change in DATRAS?

**Comment by casperwberg** [comment]
There was a similar problem with some of the early Q1 NS-IBTS data
(1992-1995).
The problem for BTS seems to be in 1998 (at least).
There are duplicated lines in the HH records (d2), which there shouldn't be.
I think the problem is on the DATRAS server side.
But a quick work-around would be to add some lines to
DATRAS:::addExtraVariables that drops any duplicated rows in HH.



Den fre. 2. feb. 2024 kl. 08.55 skrev Iago Mosqueira <
***@***.***>:

**Comment by iagomosqueira** [comment]
Thanks, found 429 double entries in 1998, yes. Will fix for now and notify DATRAS.
